name: Linting and Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main

jobs:
  lint-unit:
    name: Lint and Unit tests
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.6", "3.8", "3.10"]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install "tox < 4" #tox has breaking changes in major version 4
    - name: Run lint checkers
      run: tox -e lint
    - name: Run unit tests
      run: tox -e unit
    - name: Save PR number to file
      run: echo ${{ github.event.number }} > PR_NUMBER.txt
    - name: Archive PR number
      uses: actions/upload-artifact@v3
      with:
        name: PR_NUMBER
        path: PR_NUMBER.txt
    - name: Save coverage report
      run: |
        report_root="/home/runner/work/charm-prometheus-juju-exporter/charm-prometheus-juju-exporter/tests/unit/report/"
        cp ${report_root}/coverage.xml cov.xml
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: ./cov.xml
